In [1]:
import time
import pandas as pd

from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB as nb
from sklearn.neighbors import KNeighborsClassifier as knn
from sklearn.linear_model import LogisticRegression as lr
from sklearn.neural_network import MLPClassifier as mlp
from sklearn.model_selection import train_test_split
import numpy as np
import pickle
import sklearn.metrics as sm
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import MultinomialNB as mnb

In [2]:
def predict_svm(X_train, X_test, y_train, y_test):
    svc=SVC(kernel='linear') 
    print("svm started")
    svc.fit(X_train,y_train)
    
    #filename = 'svm_model.sav'
    #pickle.dump(svc, open(filename, 'wb'))
    
    y_pred=svc.predict(X_test)
    print(classification_report(y_test,y_pred))
    print("--------------------")
    print(confusion_matrix(y_test,y_pred))
    #calc_accuracy("SVM",y_test,y_pred)

In [3]:
def predict_mnb(X_train, X_test, y_train, y_test):
    clf = mnb()
    print("mnb started")
    clf.fit(X_train,y_train)
    
    #filename = 'nb_model.sav'
    #pickle.dump(clf, open(filename, 'wb'))
    
    y_pred=clf.predict(X_test)
    print(classification_report(y_test,y_pred))
    print("--------------------")
    print(confusion_matrix(y_test,y_pred))

In [4]:
def predict_lr(X_train, X_test, y_train, y_test):
    clf = lr()
    print("lr started")
    clf.fit(X_train,y_train)
    
    #filename = 'lr_model.sav'
    #pickle.dump(clf, open(filename, 'wb'))
    
    y_pred=clf.predict(X_test)
    print(classification_report(y_test,y_pred))
    print("--------------------")
    print(confusion_matrix(y_test,y_pred))
    #calc_accuracy("Logistic regression",y_test,y_pred)

In [5]:
def predict_rf(X_train, X_test, y_train, y_test):
    rtree=RandomForestClassifier(n_estimators=200)
    print("rf started")
    rtree.fit(X_train,y_train)
    y_pred=rtree.predict(X_test)
    print(classification_report(y_test,y_pred))
    print("--------------------")
    print(confusion_matrix(y_test,y_pred))
    

In [6]:
def predict_nb(X_train, X_test, y_train, y_test):
    clf = nb()
    print("nb started")
    clf.fit(X_train,y_train)
    
    #filename = 'nb_model.sav'
    #pickle.dump(clf, open(filename, 'wb'))
    
    y_pred=clf.predict(X_test)
    print(classification_report(y_test,y_pred))
    print("--------------------")
    print(confusion_matrix(y_test,y_pred))
    #calc_accuracy("Naive Bayes",y_test,y_pred)

In [7]:
def predict_knn(X_train, X_test, y_train, y_test):
    clf=knn(n_neighbors=8)
    print("knn started")
    clf.fit(X_train,y_train)
    
    #filename = 'knn_model.sav'
    #pickle.dump(clf, open(filename, 'wb'))
    
    y_pred=clf.predict(X_test)
    print(classification_report(y_test,y_pred))
    print("--------------------")
    print(confusion_matrix(y_test,y_pred))
    #calc_accuracy("K nearest neighbours",y_test,y_pred)

In [8]:
def predict_mlp(X_train, X_test, y_train, y_test):
    clf=mlp()
    print("mlp started")
    clf.fit(X_train,y_train)
    
    #filename = 'mlp_model.sav'
    #pickle.dump(clf, open(filename, 'wb'))
    
    y_pred=clf.predict(X_test)
    print(classification_report(y_test,y_pred))
    print("--------------------")
    print(confusion_matrix(y_test,y_pred))
    #calc_accuracy("MLP classifier",y_test,y_pred)


In [9]:
df = pd.read_csv(r"C:\Users\98anm\Desktop\ANMOL\DATA SCIENCE 2\ML PROJECTS\minorp\DETECTION11.csv", sep=',',header=None)
X = df.iloc[:, :-1]
y = df.iloc[:,-1]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

In [10]:
df.head()

0         1         2         3         4         5         6     \
0  0.540932  0.231248  0.540932  0.251596  0.540932  0.542417  0.308191   
1  0.446216  0.446216  0.446216  0.446216  0.446216  0.459399  0.388874   
2  0.109357  0.341113  0.833411  0.400502  0.091602  0.134118  0.667845   
3  0.616773  0.265767  0.269680  0.299439  0.616773  0.370401  0.480568   
4  0.446216  0.446216  0.446216  0.446216  0.446216  0.446216  0.446216   

       7         8         9     ...       7991      7992      7993      7994  \
0  0.542417  0.130199  0.542417  ...   0.459509  0.459509  0.459509  0.459509   
1  0.459399  0.459399  0.459399  ...   0.509970  0.509970  0.509970  0.351733   
2  0.667845  0.231959  0.171776  ...   0.446216  0.446216  0.446216  0.446216   
3  0.480568  0.480568  0.406407  ...   0.604514  0.604514  0.274891  0.297644   
4  0.446216  0.446216  0.446216  ...   0.446216  0.446216  0.446216  0.446216   

       7995      7996      7997      7998      7999  8000  
0  0.138177  0.482382  0.565746  0.565746  0.320044  FIRE  
1  0.470566  0.470566  0.470566  0.470566  0.331014  FIRE  
2  0.394789  0.359101  0.486596  0.486596  0.486596  FIRE  
3  0.446216  0.446216  0.446216  0.446216  0.446216  FIRE  
4  0.461691  0.461691  0.458531  0.381656  0.461691  FIRE  

[5 rows x 8001 columns]

In [11]:
#predict_svm(X_train, X_test,y_train, y_test)
#predict_knn(X_train, X_test,y_train, y_test)
predict_lr(X_train, X_test,y_train, y_test)
#predict_nb(X_train, X_test,y_train, y_test)
#predict_mlp(X_train, X_test,y_train, y_test)

lr started
             precision    recall  f1-score   support

       FIRE       0.98      0.97      0.97       316
     NOFIRE       0.95      0.96      0.96       199

avg / total       0.97      0.97      0.97       515

--------------------
[[305  11]
 [  7 192]]


In [12]:
predict_svm(X_train, X_test,y_train, y_test)
#predict_knn(X_train, X_test,y_train, y_test)
#predict_lr(X_train, X_test,y_train, y_test)
#predict_nb(X_train, X_test,y_train, y_test)
#predict_mlp(X_train, X_test,y_train, y_test)

svm started
             precision    recall  f1-score   support

       FIRE       0.97      0.92      0.95       316
     NOFIRE       0.89      0.95      0.92       199

avg / total       0.94      0.94      0.94       515

--------------------
[[292  24]
 [  9 190]]


In [13]:
#predict_svm(X_train, X_test,y_train, y_test)
predict_knn(X_train, X_test,y_train, y_test)
#predict_lr(X_train, X_test,y_train, y_test)
#predict_nb(X_train, X_test,y_train, y_test)
#predict_mlp(X_train, X_test,y_train, y_test)

knn started
             precision    recall  f1-score   support

       FIRE       1.00      0.26      0.41       316
     NOFIRE       0.46      1.00      0.63       199

avg / total       0.79      0.54      0.49       515

--------------------
[[ 81 235]
 [  0 199]]


In [14]:
#predict_svm(X_train, X_test,y_train, y_test)
#predict_knn(X_train, X_test,y_train, y_test)
#predict_lr(X_train, X_test,y_train, y_test)
predict_nb(X_train, X_test,y_train, y_test)
#predict_mlp(X_train, X_test,y_train, y_test)

nb started
             precision    recall  f1-score   support

       FIRE       0.87      0.52      0.65       316
     NOFIRE       0.53      0.88      0.66       199

avg / total       0.74      0.66      0.65       515

--------------------
[[163 153]
 [ 24 175]]


In [15]:
#predict_svm(X_train, X_test,y_train, y_test)
#predict_knn(X_train, X_test,y_train, y_test)
#predict_lr(X_train, X_test,y_train, y_test)
#predict_nb(X_train, X_test,y_train, y_test)
predict_mlp(X_train, X_test,y_train, y_test)

mlp started
             precision    recall  f1-score   support

       FIRE       0.61      1.00      0.76       316
     NOFIRE       0.00      0.00      0.00       199

avg / total       0.38      0.61      0.47       515

--------------------
[[316   0]
 [199   0]]


D:\python_anaconda\lib\site-packages\sklearn\metrics\classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
